# Generated by Django 4.1.3 on 2022-12-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
